[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true
dotenv = true # Explicitly tell Foundry to load the .env file

[rpc_endpoints]
amoy = "${AMOY_RPC_URL}" # Create a "amoy" alias for the URL in your .env
